version: "3.9"
services:
  jobmanager:
    image: dejareve:latest
    container_name: jobmanager
    volumes:
      - ./app:/opt/app
    hostname: "jobmanager"
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  taskmanager:
    image: dejareve:latest
    container_name: taskmanager
    volumes:
      - ./app:/opt/app
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - jobmanager:jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=20
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "transactions:1:1,temp_result:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  data_generator:
    image: data_generator:latest
    container_name: data_generator
    command:
      ["bash", "./wait_for_kafka.sh", "python", "transaction_generator.py"]
    depends_on:
      - kafka
      - jobmanager
